### ISSUE TITLE
Enable\Disable Drawer

### ISSUE THREAD

**Issue by chinswain** [leocb/MaterialSkin#100]
Is it possible to disable the drawer from poping out?

**Comment by leocb** [comment]
You mean leaving the drawer always open? This was discussed in #95 and it's not recommend, but should be possible, see my comments on that issue.

If you mean you want the drawer to completely close, uncheck the `drawer show icons when hidden` in the form's property

If you mean you don't want a drawer at all, simply clear the `DrawerTabControl` from the form's property

**Comment by chinswain** [comment]
I have a child form that opens in front of the parent to show progress, I don't want the user to be able to open the drawer menu at all. I loop through all of the controls on the parent form when opening the child to disable them all but this does not effect the drawer. I would like to be able to prevent it's use while the child window is open. I tried clearing DrawerTabControl but when I try to set it back the drawer no longer works.

**Comment by leocb** [comment]
try to set the Owner property of the child form, you can't do anything else on the parent form until the child is closed
