### ISSUE TITLE
maskedTextBox?

### ISSUE THREAD

**Issue by N1x0** [leocb/MaterialSkin#103]
Hi there so I wanted to know if it's possible to implement a maskedtextbox. I know there are other ways to validate data but the maskedtextbox is actually sufficient for most basic usecases.

**Comment by leocb** [comment]
Hi, it's possible, but not planned in the near (or far) future.
At the moment, the only supported thing on the textbox is a `password` feature that hides what's written on it.
If you manage to implement it yourself, feel free to open a PR
