### ISSUE TITLE
ShowDialog() not returning after form fully loads

### ISSUE THREAD

**Issue by jbradleyisland** [leocb/MaterialSkin#105]
Hello, thank you for the work you've done in producing and maintaining this package - it has made designing with winforms much more pleasant and enjoyable.

I'm having an issue with having a MaterialForm return from form.ShowDialog() in my application - basically I have two MaterialForms, one is a login form and the other is the main application. When I call the login form everything loads up cleanly but upon this.Close() nothing is returning to the main function:

`DialogResult result;

using (LoginForm1 lf = new LoginForm1())
    result = lf.ShowDialog();

if (result == DialogResult.OK)
{
    Application.Run(new LibraryForm());
}
else
{
    Application.Exit();
}`

I've testing my code using standard a winform form with standard controls without issue. I think it is related to form disposal but I'm not certain how to check for this. Please advise if there is any other pertinent information I may be able to provide to help determine the issue here. Thanks!

**Comment by leocb** [comment]
Hi, I'm glad you like it :)
This is an known issue when creating projects with a .net version different than the lib, see #67 
Could you check if this is also your case? Thanks

**Comment by jbradleyisland** [comment]
You know, I originally checked through the wrong MaterialSkin github before realizing I was using your release. It looks like it is the same issue. I am using 4.7.2 and didn't realize the lib was in 4.6.1

Implementing the workaround they posted works for me!

**Comment by leocb** [comment]
Glad I could help. :)
