### ISSUE TITLE
Dark Theme and dynamically added control

### ISSUE THREAD

**Issue by ThibaudMZN** [leocb/MaterialSkin#107]
Hi, 
I'm running into a strange and really specific issue with the dark theme.

When creating a custom control with a panel, and adding it in designer mode into a Form, everything works fine with dark mode. But if I had it by script, then it seems like the MaterialSkinManager cannot access the custom control background and leave it white. 

This is how I had the custom control :

`
            CustomControl customControl = new CustomControl();
            flowLayoutPanel.Controls.Add(customControl);
`

You can see below a picture illustrating this behavior, on the left the custom control added from designer mode, and on the right the one added by script.

Any idea on why this is happening would be appreciated, maybe I need to force the background manually ?

Thanks !

![Capture](https://user-images.githubusercontent.com/1643465/91674636-1bab6980-eaff-11ea-8592-ad295bb16ace.PNG)

**Comment by leocb** [comment]
Hi, you must change the background color on code or enable "enforce back color" as in this wiki entry https://github.com/leocb/MaterialSkin/wiki/FAQ#backcolor-property-on-non-material-components

**Comment by ThibaudMZN** [comment]
Hey, both of those solutions are not working, the "EnforceBackColor" is already set to on, and copying the designer code doesn't work either. I suspect this is a bug due to the order in which the controls are colored and added ?

**Comment by leocb** [comment]
The flow layout may be breaking something, could you text adding the panel directly to the form?

**Comment by ThibaudMZN** [comment]
I tried with a tabControl and also by adding it directly to the form, and still have the same behavior !

**Comment by ThibaudMZN** [comment]
I tried with a tabControl and also by adding it directly to the form, and still have the same behavior !

**Comment by leocb** [comment]
Weird, are you overriding the onPaint function on your control?
Could you try a simple panel? (not a custom control)

**Comment by ThibaudMZN** [comment]
I'm not overriding the onPaint function no, and yes it works with a simple panel ! Where is in the library the code that actually sets the Dark BackgroundColor ? Maybe it's missing a loop on inner controls

**Comment by ThibaudMZN** [comment]
I manage to solve this issue by calling the AddFormToManage function or setting the theme after dynamically adding the control, since those functions calls the private UpdateBackgrounds function.

Though, this is not ideal because in the case of a desktop App i'm working on, controls are added after all of the form management function are called.

May I suggest adding a public function to MaterialSkinManager to be able to force the background on a newly added control ? I can work on this and make a PR if you think that's the best approach !

**Comment by ThibaudMZN** [comment]
Maybe the best option would be to add a public function to MaterialSkinManager to set the background color on a specific control, and then add an event listener on the MaterialForm itself to check for ControlAdded and apply the correct Background on it !

**Comment by leocb** [comment]
Thanks for the fix!

**Comment by ThibaudMZN** [comment]
No problem !
