### ISSUE TITLE
Autocomplete textbox

### ISSUE THREAD

**Issue by princ3od** [leocb/MaterialSkin#118]
- MaterialTextbox is inherited from RichTextbox. But richtextbox does not have Autocomplete property, so it make MaterialTextbox hard to implement suggestion.
 - I do not why don't inherite from Textbox instead of RichTextbox?
- Hope you take a look at this. Thank you.

**Comment by leocb** [comment]
Hi, this is a duplicate from #64 
Thanks for the suggestion
