### ISSUE TITLE
Bug when started as Administrator

### ISSUE THREAD

**Issue by LaTecnologia24** [leocb/MaterialSkin#119]
When I start it as an administrator and minimize an invisible form that prevents it from returning the second time

![Immagine 2020-11-14 235402](https://user-images.githubusercontent.com/33404214/99158623-00e79a80-26d5-11eb-9a02-26d839ea7ed1.png)

This append only if enable DrawerTabControl = materialTabControl1 before compiling in form settings.

**Comment by leocb** [comment]
Hi, thanks for reporting!
This is a known issue, no solution yet.
It's being tracked in #75 
Marking this as duplicate, please follow that issue

Thanks again
