### ISSUE TITLE
Disabling form title bar

### ISSUE THREAD

**Issue by tiagossa1** [leocb/MaterialSkin#123]
Hello! First of all, thanks for keep this project alive!
Is there any way that I can hide/remove the title bar?

Here's an example of what I'm talking about:
![image](https://user-images.githubusercontent.com/39096494/102600344-9af89380-4116-11eb-96d8-74baff44394f.png)

Thank you! :D

**Comment by leocb** [comment]
Hi, this is not supported atm but is a planned option

You can remove it by deleting/commenting the lines 895 to 950 and also line 811 on the file MaterialSkin/Controls/MaterialForm.cs. this should not have any consequences if you're not using the drawer menu.

**Comment by orapps44** [comment]
This is now possible with #185 using FormStyle property.
