### ISSUE TITLE
Button AutoSize Reset Issue

### ISSUE THREAD

**Issue by PixelDevelopers** [leocb/MaterialSkin#125]
Whenever I change the buttons from GrowAndShrink to Just Grow. So the autosize stops and I can manually set my button sizes. Whenever I close Visual Studios Designer and reopen, the button size resets as the property is reset. 

There must be something in the initialisation of the control that resets this control rather than pick up the property.

**Comment by leocb** [comment]
`Only grow` is completely ignored, please don't use it.
Simply set the autosize property to false and you should be able to resize the button to any size you'd like
