### ISSUE TITLE
Application hang when using MaterialTextBox type password on dialog/form

### ISSUE THREAD

**Issue by emgie123** [leocb/MaterialSkin#129]
Hi,

I am facing weird issue. When using a form as a dialog (opened by ShowDialog) which has MaterialTextBox of type password the application hangs on close of the dialog. The dialog closes itself but that` all. The main window is now freezed (or rather the dialog did not return the control to the main window?). If i use MaterialTextBox of text type there is no such problem - the dialog closes as normal and returns the dialog result. When pausing the execution in VS it always stops in overriden WndProc method.
Just checked: f I open the form with .Show() method the issue still remains so it is no difference if it is Show or ShowDialog. The case is that on the form the is textbox type password (meanwhile I use it also on the main form and it works)

**Comment by leocb** [comment]
Thanks for reporting, this may be related to #67, try changing your. Net target version

**Comment by emgie123** [comment]
Hi, somehow have missed thoses issues but thankfully setting .text to string empty on dispose solved the problem. Probably chaning .net version will fix it too. Thank you!
