### ISSUE TITLE
Drawer cannot scroll

### ISSUE THREAD

**Issue by hadistwn22** [leocb/MaterialSkin#142]
Hi..
Nice framework :D
But I cant scroll in drawer..
Is it possible to scrolling in drawer?

Thanks..

**Comment by leocb** [comment]
Hi, thanks for asking
Possible? Yes
Planed? No
I think scrolling the drawer should be a bad user experience, maybe 5 try increasing the firm  height?

**Comment by hadistwn22** [comment]
Okay..
Thanks.. :D
