### ISSUE TITLE
MaterialMessageBox: Icons cut off

### ISSUE THREAD

**Issue by paleiadevelopment** [leocb/MaterialSkin#148]
When displaying a MaterialMessageBox with an icon, the icon is cut off if the message text is not long enough to have enough lines.

Expected behaviour: The MessageBox should change its size automatically to accomodate the icon, like it does with "normal" Message Boxes.

![messageboxicon](https://user-images.githubusercontent.com/67471820/109381706-35760f80-78dc-11eb-9629-2fcfd0b1438a.PNG)

**Comment by leocb** [comment]
Thanks for reporting.
There's no support for icons on the message box. 
Also, please don't use the windows default icons on your app, that breaks a lot of material design iconography rules :)
