### ISSUE TITLE
Buttons: "&" shown in button text

### ISSUE THREAD

**Issue by paleiadevelopment** [leocb/MaterialSkin#149]
In all places where buttons are used (MaterialButton, the Buttons in MaterialMessageBox), having a &Whatever in the control.text property instead of underlining that letter and using it as a keyboard shortcut, will show the & in the button text.

Expected behaviour: An & in the control.text property should underline that letter in the displayed control and use it as the keyboard shortcut.

**Comment by leocb** [comment]
Yes, this is not supported at the moment

**Comment by paleiadevelopment** [comment]
How can I disable this, then?
I have a ton of message boxes, where all "Yes" and "no" buttons do this. Since the texts for these are set by the OS; I can't seem to change it...
