### ISSUE TITLE
MaterialForm: Can not get resizing to work

### ISSUE THREAD

**Issue by paleiadevelopment** [leocb/MaterialSkin#150]
I'm probably just stupid, but I just can't get a MaterialForm to resize using the resize handles without setting the borderstyle to anything but "none". But if I do that, I get the default Windows title bar.
I looked for documentation, but could not find anything. It makes no difference if Form.Resizable is True or False.

**Comment by leocb** [comment]
Take a look at the example app, there should be a padding in the form, ie: all containers must leave a 5 or so pixel gap to the form border, then the resize should work.

**Comment by paleiadevelopment** [comment]
I'm afraid it doesn't. I even tried 50 pixels - I see the padding, but it does not resize :(
