### ISSUE TITLE
Cursor blinking

### ISSUE THREAD

**Issue by helperman** [leocb/MaterialSkin#151]
Could you please fix the annoyin issue?
https://youtu.be/Gu8ykcTe-70

The issue happens with almost each control on mouse hover.

**Comment by leocb** [comment]
Thabks for reporting.
What version are you on? Seems like a bug introduced in the latest version

**Comment by helperman** [comment]
I downloaded the latest version 2.1.4 and launched a demo-application.
This issue also hurts CPU-performance: it becomes too high at that moments.

**Comment by orapps44** [comment]
I noticed same issue, I'm gonna check that asap.

**Comment by GHNJ** [comment]
Hi, is there an update to this issue? I noticed that it does spike the CPU and quite a bit. thanks.

**Comment by leocb** [comment]
Yes, this is fixed on master, but not yet released in a nugget. For now You can use the previous nugget version or compile from master

**Comment by GHNJ** [comment]
great thanks!

**Comment by orapps44** [comment]
Fixed with last release (2.2.0).
