### ISSUE TITLE
Drawer Scroll Option

### ISSUE THREAD

**Issue by KristanSmout** [leocb/MaterialSkin#162]
It would be nice to have the ability to have the option to enable scrolling on the Drawer, other than that I would consider it perfect so regardless well done this is a really nice thing to use. 

Edit: I have created this for my own personal use so can offer a pull to have it added as a toggleable option for people if they would like it :)

https://github.com/leocb/MaterialSkin/pull/163

**Comment by leocb** [comment]
hi, if you please could rebase that PR, it'd really like to merge it, thanks

**Comment by KristanSmout** [comment]
Sure, I'll send it over in the next day or so when i get a chance :)

**Comment by orapps44** [comment]
Feature added with PR #306
