### ISSUE TITLE
MultiLineTextBox  disable in dark theme : the text is not visible.

### ISSUE THREAD

**Issue by Nardo26000** [leocb/MaterialSkin#164]
When the Dark theme is selected, the text in MultiLineTextBox is not visible.
-> materialMultiLineTextBox1.Enabled = false;

![MultiLineTexBox](https://user-images.githubusercontent.com/79220283/111903529-023e2080-8a43-11eb-8fe1-a991ff97bd68.png)

**Comment by orapps44** [comment]
That issue may not be easy to fix.
I suggest to use readonly property instead.

**Comment by orapps44** [comment]
Hi @Nardo26000 ,

Try out this alternate control, it fix this issue.
