### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by xxxmpsxxx** [leocb/MaterialSkin#166]
Hello...
How can i change de font size? Because the font Roboto 12 is very big.
Thanks.

**Comment by leocb** [comment]
Hi, font sizes are hardcoded, this ensures people adhere to the [material design type scale](https://material.io/design/typography/the-type-system.html#type-scale). I usually recommend that people should simplify their interfaces, not make font smaller so they can fit more.

However, if you reaaaaaaaally need to change the font size, modify them [in this line of the Material skin manager.cs](https://github.com/leocb/MaterialSkin/blob/d0aac0176d44e9e9ce69154112af5edb5e4c4671/MaterialSkin/MaterialSkinManager.cs#L60)
