### ISSUE TITLE
Not an issue - merge pull requests?

### ISSUE THREAD

**Issue by paleiadevelopment** [leocb/MaterialSkin#171]
This is not an issue, but I found no other way of leaving a message.
There have been a lot of very nice pull requests lately that are open. I hope they can make it  it into a release soon. :)

**Comment by leocb** [comment]
Thanks for reaching out, I'm not actively upsetting this project, do nerves and pull request will happen when I have time ™

**Comment by leocb** [comment]
Good news, I'll try to publish all the PRs this weekend on a new 2.2 version, as long as people solve the conflicts on time hehe
