### ISSUE TITLE
Button icons are greyscale

### ISSUE THREAD

**Issue by paleiadevelopment** [leocb/MaterialSkin#173]
Using the very newest master branch as of today, all icons in all MaterialsButtons are shown in greyscale.
I assume this has something to do with the new button theming.
Can this be turned off? I need icons to retain their colour :)

**Comment by leocb** [comment]
this is a material design library, It's not good practice to use colors on icons with material design. Please see the iconography section of the design guidelines.

This was actually a missing feature and is desirable.
