### ISSUE TITLE
Problems with MaterialMessageBox text label and Show method behavior

### ISSUE THREAD

**Issue by mateusmlo** [leocb/MaterialSkin#174]
I've been using a few MaterialMessageBox.Show in a project and this component shows a few weird behaviors, which I'll list below:
(the texts on the prints are in brazilian portuguese but I've translated what they say in the snippets)

The label background is diferent than the box's background (which is a darker gray).
![image](https://user-images.githubusercontent.com/13263031/117881559-c0319e00-b27f-11eb-9b3b-6f8cc603a2e3.png)
`MaterialMessageBox.Show(this, "Fill the client's name", "Warning!", MessageBoxButtons.OK);`

Calling MaterialMessageBox.Show with a MessageBoxButtons.YesNo causes a default text to appear, I believe this is due to the buttons not having been translated (I can help with this). Also, the "Success" caption does not show like above.
![image](https://user-images.githubusercontent.com/13263031/117881712-f53df080-b27f-11eb-8e34-b134608db954.png)
`MaterialMessageBox.Show(this, "File saved succesfully. Do you want to continue?", "Success", MessageBoxButtons.YesNo`

**Comment by orapps44** [comment]
Looks similar to #156 and #149.
This issue should be allready fixed on master, but not yet released in a nugget. 
Try to compile from master and post a message if it solve or not the issue.

Brazilian portuguese isn't yet supported, so you can propose a PR to add it.

**Comment by orapps44** [comment]
Fixed with last release (2.2.0).
