### ISSUE TITLE
Form Stuck on Dispose

### ISSUE THREAD

**Issue by Dolefly** [leocb/MaterialSkin#175]
When you exit the application, it got stuck here

>  protected override void Dispose(bool disposing)
>         {
>            if (disposing && (components != null))
>                 //if (disposing)
>                 {
>                 components.Dispose();
>                
>             }
>             base.Dispose(disposing);
>         }
>

**Comment by Dolefly** [comment]
Actually this happens when you are closing the child form! The Parent form freezes!

**Comment by orapps44** [comment]
Are you using last release or actual master code ?
If you are using last release then try to compile from master.

**Comment by Dolefly** [comment]
Problem solved! While checking conditions on control such as material button, checking for empty textboxes, wrap with try,catch. My code was trapped in  a loop after executing a method. After wrapping with try catch everything was ok.
