### ISSUE TITLE
Control Dock = top or fill problem

### ISSUE THREAD

**Issue by xxtkidxx** [leocb/MaterialSkin#182]
Hi team.
How to use Control Dock properties equal TOP or FILL  do not cover top Header of Form?
Thanks for support.
![image](https://user-images.githubusercontent.com/11498673/120179516-df936980-c234-11eb-8778-f81637624618.png)

**Comment by orapps44** [comment]
Instead of control dock property = fill,  i'm using Anchor =Top, Bottom, Left, Right.

**Comment by xxtkidxx** [comment]
> Hi,
> 
> You can try to set main form top padding to 80.
> 
> Instead of control dock property = fill, i'm using Anchor =Top, Bottom, Left, Right with Location.Y property set to 80.

That a good ideas, Thanks.
