### ISSUE TITLE
Remove the built-in FormBorder

### ISSUE THREAD

**Issue by imohuan** [leocb/MaterialSkin#190]
![image](https://user-images.githubusercontent.com/41279222/122156468-9c273500-ce9b-11eb-9822-22e0cc3583b5.png)

I don't like this style. I want to write it myself

**Comment by orapps44** [comment]
Ok, feel free to contribute by doing a Pull Request.

**Comment by leocb** [comment]
Poor soul, you have no idea what you're getting in to. Handling the window events by hand is one of the worst nightmares you can face when doing custom interfaces for windows.
