### ISSUE TITLE
It gets slower within time

### ISSUE THREAD

**Issue by setwebdreams** [leocb/MaterialSkin#191]
The application gets slower when forms are opened and closed many times (1000 times).

After this, the application consumes a lot of CPU.

I detected that after commenting OnGlobakMouseMove on MaterialForm the issue is solved.

`            // This enables the form to trigger the MouseMove event even when mouse is over another control
            //Application.AddMessageFilter(new MouseMessageFilter());
            //MouseMessageFilter.MouseMove += OnGlobalMouseMove;
`

**Comment by orapps44** [comment]
Hi,  

Thanks for reporting this issue.

Another benefit of commenting those lines is to solve issue #154.

But side effect of that is resizing around drwer edge won't work unti another way is found.
