### ISSUE TITLE
No shadow under cards

### ISSUE THREAD

**Issue by Ilya00111** [leocb/MaterialSkin#198]
Hey everyone, recently I installed MaterialSkin pack in my Windows Forms project and I noticed that there is no shadow under the cards and they are not perfectly visible on a white background. I explored the example project and ran it on my PC and the cards were perfectly visible on a white background and had a shadow. There is something wrong with them... :(

![Screenshot_2](https://user-images.githubusercontent.com/87602973/126064650-0d134367-627b-4cdc-9add-ec819e6ac922.png)
![Screenshot_3](https://user-images.githubusercontent.com/87602973/126064651-5d5abf5e-22cb-4087-90d3-3dec966202b9.png)

```
using MaterialSkin;
using MaterialSkin.Controls;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace wfn1
{
    public partial class Form1 : MaterialForm
    {
        public Form1()
        {
            InitializeComponent();
            var materialSkinManager = MaterialSkinManager.Instance;
            materialSkinManager.EnforceBackcolorOnAllComponents = false;
            materialSkinManager.AddFormToManage(this);
            materialSkinManager.Theme = MaterialSkinManager.Themes.LIGHT;
            materialSkinManager.ColorScheme = new ColorScheme(Primary.Amber800, Primary.Amber900, Primary.Amber500, Accent.Amber200, TextShade.WHITE);
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void materialCard1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
```

**Comment by paleiadevelopment** [comment]
I have the same issue, have never been able to get shadows to work.

**Comment by orapps44** [comment]
Obviously to make shadow works properly controls must be in a container.
Try to put them in a panel docked to your form.

**Comment by Ilya00111** [comment]
Yay! I placed tab control in my app and now cards are working perfectly! Beautiful shadows are perfectly visible on any background. Thanks for help, @orapps44  and @paleiadevelopment.
