### ISSUE TITLE
Table Header is broken on systems without Roboto Font installed

### ISSUE THREAD

**Issue by leocb** [leocb/MaterialSkin#2]
![image_2019_10_04T21_52_28_756Z](https://user-images.githubusercontent.com/8310271/66242535-2c2d4700-e6d8-11e9-93f6-d438887094de.png)

**Comment by leocb** [comment]
seems to be releated to #19

**Comment by leocb** [comment]
Probably fixed on #24 further testing is still required

**Comment by goto3** [comment]
Hello, Is there a fix for this?
Thank you

**Comment by leocb** [comment]
Hi, I did not fix this yet. It happens when the users doesn't have the font installed on their system. I'm still looking for a fix.

I'm not sure it'll work, but try this: Modify the table control to force it to a default windows font and set the size so it'll have the correct height.

Since I ignore the font completly when drawing, the Font property will, theoretically, only affect the size.

This component is not very obedient to user paint events, I'm still figuring it out. my GoogleFu, as strong as it is, did not help me much when developing this one.

If you manage to fix it, please open a PR :)
cheers

**Comment by goto3** [comment]
I commented these lines on MaterialListView:

![image](https://user-images.githubusercontent.com/16456164/68889995-ce3f4680-06fc-11ea-99ab-6dc3d289a846.png)

and now it looks like this:

![image](https://user-images.githubusercontent.com/16456164/68890022-da2b0880-06fc-11ea-9c8e-358e3142b832.png)

that is good enough for me

**Comment by leocb** [comment]
Looks like my `Font` property hunch was right haha.
If possible, please test it with the font also installed on your system, it may yield different results.
If it's working correctly, please open a PR with the changes (and please delete the lines, no commented code on PRs 😅)
Happy coding!
