### ISSUE TITLE
Combo box text error

### ISSUE THREAD

**Issue by seoyeon01** [leocb/MaterialSkin#20]
![2](https://user-images.githubusercontent.com/48429544/66637982-1b884e00-ec4f-11e9-9d12-6214ae3b7991.gif)
Text in combobox is not output normally.

**Comment by leocb** [comment]
That's the windows forms default behavior, if you want it to show an item from the beginning, you have to program that.
![image](https://user-images.githubusercontent.com/8310271/66651785-4bf9c900-ec0a-11e9-9b8f-049ff48f8bc3.png)

You can do it by adding the following line on the form code:
``` C#
materialComboBox1.SelectedIndex = 0;
```

**Comment by seoyeon01** [comment]
No... 
![text](https://user-images.githubusercontent.com/48429544/66712681-1ce68180-eddb-11e9-93e7-35621ef3637b.jpg)
This means that the text is not rendered properly and it is becoming lumpy.

**Comment by leocb** [comment]
Oh I can see it now
The code for the combo box control has been redone, could you please try the latest version from master and see if this still happens?

**Comment by seoyeon01** [comment]
![2](https://user-images.githubusercontent.com/48429544/66717928-0fe88300-ee19-11e9-8354-655938c87259.gif)
The text now appears correctly in the text box.

However, the problem still occurs when the mouse is over in the dropdown list.

**Comment by leocb** [comment]
That's so weird, I've never seen anything like it. I'll have to investigate more.
Could you please post your system specs, windows version and DPI settings (windows scaling)?

**Comment by seoyeon01** [comment]
I7-8000 / 16GB ram / GTX1060 3gb / windows10 pro 64bit / 1920x1080 100%DPI
thanks.

**Comment by seoyeon01** [comment]
I was able to confirm a few more facts.

Mouseover from the list does not cause problems for the currently selected item.

for example

**[ 3. item 3 ]**
ㅡㅡㅡㅡㅡ
| 1. Item 1  |
| 2. item 2 |
| 3. Item 3 |
| 4. Item 4 |
| 5. item 5 |
ㅡㅡㅡㅡㅡ
There is nothing wrong with placing your mouse on No. 3 of the list. However, there is a problem when you hover your mouse over other items.

**Comment by seoyeon01** [comment]
![image](https://user-images.githubusercontent.com/48429544/66733523-d0fb1180-ee9a-11e9-9586-a4ee5f825af7.png)
Is this a problem caused by my own wrong way?
This has not happened in the release of 2.0.0ver.

This error occurs when i download the master and open MainForm.cs
"The control has been disabled by through an exception that has not been processed by the designer."
Exception : The index and length must refer to a location within the string.
Parameter name : length
MaterialSkin.Controls.MaterialComboBox.OnPaint(PaintEventArgs pevent) File
...\MaterialSkin-master\MaterialSkin-master\MaterialSkin\Controls\MaterialComboBox.cs : line 221
![image](https://user-images.githubusercontent.com/48429544/66733820-c3925700-ee9b-11e9-88cb-617a5762ee20.png)

**Comment by leocb** [comment]
If you're using the latest master, it's unstable and may have breaking bugs, so it's my fault you're seeing these errors, that piece of code shouldn't be there for example. If you want "stable" code, use the release version only.

Now for the draw bug reported here and on #22 - I really can't see any problems on my code that would cause this behavior, it seems like a display driver bug to me. Make sure you have the latest driver installed from nvidia AND intel, most likely you're using old intel drivers that may have some bug on WDDM.

But I'll keep looking for any weird code.

**Comment by leocb** [comment]
Hi @seoyeon01, did you manage to get these issues fixed? I'd love to hear some feedback

**Comment by leocb** [comment]
I will be closing this for now, if you continue to have problems, feel free to open it again
