### ISSUE TITLE
Added CharacterCasing to MaterialTextbox

### ISSUE THREAD

**Issue by Rillwz** [leocb/MaterialSkin#200]
it seems that the textbox component lacks the character casing feature which in the original textbox winform component is used to set the default values ​​for the uppercase and lowercase characters. can we add this feature.

![image](https://user-images.githubusercontent.com/73714271/127310362-490537ea-5407-49ed-a439-42f3d537b63f.png)
![image](https://user-images.githubusercontent.com/73714271/127310462-eebd1908-5bd0-41a7-9558-e65f42f62381.png)

**Comment by orapps44** [comment]
Use new MaterialTextBox2 control instead to get this property.
