### ISSUE TITLE
why I run MaterialSkinExample as administrator then minimize the window to the taskbar

### ISSUE THREAD

**Issue by hwenjun** [leocb/MaterialSkin#202]
1/ run MaterialSkinExample application as administrator
2/ minimize the window to the taskbar
3/ Re-click the application under the taskbar
4/ The MaterialSkinExample can't open.

I find on paint event didn't be firing in material form class run as administrator, I attemp to override WndProc to get the message which indicate the form has been activated and force form to Invalidate, but it doesn't work.I hope you can check codes and I want to know why it is.Anyway, I like material concept.

**Comment by leocb** [comment]
Duplicated #75
