### ISSUE TITLE
I run MaterialSkinExample project as an administrator, then minimize the app to the taskbar, reclick the app on the taskbar but it didn't show.

### ISSUE THREAD

**Issue by hwenjun** [leocb/MaterialSkin#203]
I run MaterialSkinExample project as an administrator, then minimize the app to the taskbar, reclick the app on the taskbar but it didn't show.
I find that when I run as an administrator, the onPaint event didn't been firing in Material Form class. I attempt to override WndProc function to get msg about this, but when I get msg and deal with this msg, I called the Invalidate function, but it didn't work.

**Comment by hwenjun** [comment]
![image](https://user-images.githubusercontent.com/26062901/129654165-5427720e-cff3-4763-85c8-f05a2a0c5a5d.png) It works.

**Comment by leocb** [comment]
Hi, this is a known issue. Please see #75 
We're tracking this issue there and would be nice to concentrate all investigations and possible solutions over there, if you would be so kind, please post this solution there, and maybe also open a PR so we can analyze and maybe merge it into the project.
Thanks for your help :)
