### ISSUE TITLE
Material TextBox Text alignment

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#209]
Hi.
Please, can you add the ability to align text in textbox control? 
On some circumstances we must align text to the right, for numeric only.

Regarding this type of control, which allows only numeric characters, you can improve control by adding some properties, like 

- IsDigit - type boolean - it will allow only digits (keys accepted: 0->9, Del, Enter, Tab, Back)
- DoNotAllowSymbols - type boolean - it will allow only digits, a-z chars, and controls keys like Del, Enter, Tab, Back. It will not allow other chars, like !@#$%^ etc

Thanks

**Comment by orapps44** [comment]
MaterialTextBox2 and MaterialMaskedTextBox include TextAlign property.

To allow only numeric data MaterialMaskedTextBox may be useful.
