### ISSUE TITLE
MaterialComboBox  Data late loading problem

### ISSUE THREAD

**Issue by TLHYKSK46** [leocb/MaterialSkin#210]
When I click on the row from the datagridView, I load data to the combobox, but when I hover the data to the combobox with the mouse, it is loaded too late.

**Comment by AlsDev-Sbin** [comment]
[ENG(TRANSLATE)]
Add some code snippet, prints so we can better understand the problem.

**Comment by TLHYKSK46** [comment]
Now I realized that issues have been opened about this problem before, actually the error I got was "ComboBox Won't Display Items if Not Focused #120" is exactly the same as the error here

**Comment by orapps44** [comment]
Hi, 
Plese use #120 to avoid duplicate open issues.
