### ISSUE TITLE
MultilineTextBox Background color it will reset itself

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#211]
Hi.
Why the Backcolor of MultilineTextBox object it resets itself to a certain value? 
For example for a MultilineTextBox  the default value is (80, 80 ,80) when I put the control on the form. But if I want to change it to (50, 50, 50) when I press enter it will reset to (80, 80, 80). 
Strange!

**Comment by orapps44** [comment]
Hi,
On all MaterialSkin controls Backcolor property can not be set. 
Described behaviour is normal.

Later I will hide this property.
