### ISSUE TITLE
Material Textbox Stuck

### ISSUE THREAD

**Issue by Dolefly** [leocb/MaterialSkin#212]
Hello,
I did compile the latest MaterialSkin from source, 15/09/2021, and after running it got stuck and on break point it was pointing Material Textbox cursor thing, see attached!

**Comment by Dolefly** [comment]
![material textbox error](https://user-images.githubusercontent.com/11732464/133391939-da8d0b9c-ee08-403a-a91a-aa675444e0eb.png)

**Comment by Dolefly** [comment]
So i had to revert back to previous version before the new merge!

**Comment by orapps44** [comment]
Hi, 

Are you talking about PR #199 merge ?

**Comment by Dolefly** [comment]
Hi, I can't tell which merge exactly but building from the current master has this bug!

**Comment by Dolefly** [comment]
Anything on this?

**Comment by orapps44** [comment]
I can't reproduce your issue, so no progress ...

Try to use MaterialTextbox2 instead.
It has been introduce recentely, so it isn't part of last release. You need to download currenter master and compile it.

**Comment by Dolefly** [comment]
The issue actually happens on the cursor flicker fix method!
