### ISSUE TITLE
Multiline TextBox Issue when typing

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#213]
Hi.
It's happening only to me or this is how it is working this control?!
When I press a key the caret position go to beginning (first position in control).
I don't have any event in KeyDown, KeyPress, or anywhere else...

**Comment by orapps44** [comment]
Hi,
I can't reproduce this behaviour.

**Comment by valimaties** [comment]
Solved:
Changed DataSourceUpdateMode to OnValidation instead of OnPropertyChanged!
[This](https://stackoverflow.com/questions/20243839/richtextbox-databinding-issue-on-typing) thread helped me!
