### ISSUE TITLE
Floating Action Button bug

### ISSUE THREAD

**Issue by seoyeon01** [leocb/MaterialSkin#22]
![fb](https://user-images.githubusercontent.com/48429544/66718003-f136bc00-ee19-11e9-9278-1928fedfd9fc.jpg)

The bottom part of the Flying Action Button has been cut.

**Comment by leocb** [comment]
When does this happen? Is the bottom image from the latest master?

**Comment by seoyeon01** [comment]
yes. 
the bottom image is the latest master.
I downloaded 13 minutes ago.

**Comment by leocb** [comment]
seems to be related to #20, we will follow this up over there.
