### ISSUE TITLE
App goes in Background processes

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#225]
Hi.
After I downloaded and used the last code something is going on on the app.
My structure of forms are (some of them, when I start application):
MainForm - LoginForm - SqlCredentialsForm.
MainForm is launched from Program.cs with `Application.Run(new MainForm())`. In MainForm, before initialization I create LoginForm and display it as modal, using `ShowDialog()`. When I close this LoginForm, my MainForm will not display anymore and exe it is moved to Background processes (in TaskManager).
If I use 2.2.1 package from NuGet it works ok. 
I don't know what is happening... Using debugger, with breakpoint to ShowDialog() it will not return to code after I close the form LoginForm.

**Comment by orapps44** [comment]
Hi,

Could you try to add owner when using ShowDialog :  `ShowDialog(this)`

**Comment by valimaties** [comment]
Ok, I've tried this, but no change... The behavior is the same! Something happening perhaps on disposing objects... I don't know..

**Comment by orapps44** [comment]
It seems an odd place to want to exit...
I think login result should be handled BEFORE the main form is even created.

Could you try this instead :

    internal static class Program
    {
        [STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(true);
            LoginForm lf = new LoginForm();
            lf.ShowDialog();
            if (lf.DialogResult== DialogResult.OK)
                Application.Run(new MainForm());
        }
    }

**Comment by valimaties** [comment]
I've tried this variant, starting with LoginForm in Program.cs, as well...
I have one week and a couple of days of searching solutions, I've tried all solutions found on stackoverflow, codeproject and so on...

**Comment by valimaties** [comment]
Below is a gif which shows my app not working with MaterialSkin project reference and working with MaterialSkin.2 v2.2.1 from NuGet. The code is unchanged !!!

![Behaviour](https://user-images.githubusercontent.com/49796453/135227588-0b2395d1-935e-475a-b058-bef8a83eca16.gif)

**Comment by orapps44** [comment]
Could you upload master from below link (without PR #223 & 224)

https://github.com/leocb/MaterialSkin/tree/2bfdcc0e3ceed14d47ecbaf23ca0c17f17d8cbde

**Comment by valimaties** [comment]
Same behavior...
![StrangeBehaviour2](https://user-images.githubusercontent.com/49796453/135280243-73cd98ec-e0e8-4f28-b1f2-1115d9444037.gif)

**Comment by orapps44** [comment]
I wasn't able to reproduce your issue with customized MaterialSkinExample (see link below) 

https://github.com/orapps44/MaterialSkin-login_test

Try it may be that could help you to find out what's issue root cause.

**Comment by valimaties** [comment]
It's an OS problem I think.
The same application I run it in Windows 7 and works ok, but on Windows 10 it goes main form in background processes.

**Comment by orapps44** [comment]
It can make it works on both windows 7 & 10.

**Comment by valimaties** [comment]
I have reinstalled MaterialSkin2 from Nuget. This one works on both W7 and W10.
Do you know which of the merge is the version on NuGet? I want to use that one and to merge those new objects into it.
Thanks

**Comment by Emrullah-Sahin** [comment]
![1](https://user-images.githubusercontent.com/28765787/136580314-9d8650be-bfa4-4d0f-9141-d6bc9d4029c1.png)
![2](https://user-images.githubusercontent.com/28765787/136580337-a8f23b3f-cd6b-4c52-be32-922724449108.png)
![3](https://user-images.githubusercontent.com/28765787/136580353-a57b6cd6-b9ce-4179-91ed-e1f9610b2918.png)

I had the similar issue it happened after i added the MSSQL Server Connection RichTextBox.WndProc function hangs on "message 1098" and giving inheritance from TextBox instead of RichTextBox fixed the problem, but now cursor position is broken :S.
![4](https://user-images.githubusercontent.com/28765787/136582398-e8bfdefe-7aa6-4b82-9e03-b3217fe18b04.png)

**Comment by orapps44** [comment]
Hi @valimaties ,

Is this issue fixed on your side ?

**Comment by valimaties** [comment]
Yes @orapps44.
Using `MaterialTextBox2` solved this issue
