### ISSUE TITLE
MaterialComboBox StartIndex property

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#228]
StartIndex property it cannot be 0 if the DataSource is null.
Personally I don't want my combobox to be populated with first record from DataSource, if DataSource is not null. I let user select which record would be selected. So, in my opinion StartIndex must be -1 by default, not 0!

On a form which has this control on it we will get ArgumentOutOfRangeException error on this property!
I recommend to set it to -1 by default, and let the user to choose it he wants the first record to be automatically selected and ONLY if DataSource is not null!

**Comment by orapps44** [comment]
This has been introduce with PR #201 

I do agree that StartIndex should be set to -1 by default.

@leocb : What do you think (you merged it) ?

**Comment by leocb** [comment]
You can revert it if you want, I agree with the behavior being the same as default from microsoft.
