### ISSUE TITLE
Visual studio crushes when open TextBox's ContextMenu Items

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#230]
Hi.
Searching for an option to hide `ContextMenu` from MaterialTextBox (I don't want to see ContextMenu when control is ReadOnly), I discovered that Visual Studio will crush when I want to see Items of ContextMenu.

**Comment by valimaties** [comment]
I forgot to write this happening in design mode.

Solving my problem:
I've added a property to hide context menu and seems to work fine for me!

```csharp
private bool _ShowContextualMenu;

[Browsable(true)]
[DisplayName("ShowContextualMenu")]
public bool ShowContextualMenu
{
    get => _ShowContextualMenu;
    set
    {
        _ShowContextualMenu = value;
        if (!value)
        {
            ContextMenuStrip = null;
        }
        Invalidate();
    }
}
```

**Comment by orapps44** [comment]
Added in PR #233.

Use property ShortcutsEnabled to enable or disable contextmenu and keyboard shortcuts.
