### ISSUE TITLE
Material TextBox Caret position and blinking issue

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#231]
Hi.
On a password TextBox, the caret will get a strange position after some characters. More than that, after a couple of blinking (4 I countered) it will stop blinking. And it will start blinking again when mouse is getting over the control.

![CaretPositionAndBlinking](https://user-images.githubusercontent.com/49796453/135848546-f498f792-7e02-48dc-ac7c-944fc41059be.gif)

(version 2.2.1 NuGet - the same behavior on the latest code)

**Comment by orapps44** [comment]
This is a known issue of release 2.2.1 allready describes in #186.
It has been partially fixed.

If using master code, you can use MaterialTextBox2 to fix it or set UseTallSize = True.
