### ISSUE TITLE
Current master crashes when software closes a form

### ISSUE THREAD

**Issue by paleiadevelopment** [leocb/MaterialSkin#239]
Hi!
Since today's commit, my software refuses to start and will show this error:
************** Ausnahmetext **************
System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "frm_startup".
   bei System.Windows.Forms.Control.CreateHandle()
   bei System.Windows.Forms.Form.CreateHandle()
   bei System.Windows.Forms.Control.get_Handle()
   bei MaterialSkin.Controls.MaterialForm.OnCreateControl() in C:\Users\Novatlan\Documents\Visual Studio 2019\Projects\MaterialSkin-master\MaterialSkin\Controls\MaterialForm.cs:Zeile 770.
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei MaterialSkin.Controls.MaterialForm.WndProc(Message& m) in C:\Users\Novatlan\Documents\Visual Studio 2019\Projects\MaterialSkin-master\MaterialSkin\Controls\MaterialForm.cs:Zeile 675.
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I have tracked it down to the fact that I have a form that opens at the start, loads another form, then closes. This seems to trigger the crash. 
If I comment out the Me.Close, it works fine. It also works fine when any other form is opened, then closed.
My suspicion is that Material Skin does not like it when the start form is closed.

Is that a bug? I see no way to work around it in my software, also given that it used to work fine until the last commit.

**Comment by paleiadevelopment** [comment]
Here's my project. I deleted everything but the start form, and deleted everything out of that form but the Me.Close and Me.Dispose.
usually right before those lines there would be another form opened by the application, then the frm_startup form closes.

Just open the project and hit F5, it shows the error immediately for me.

[Crashtest.zip](https://github.com/leocb/MaterialSkin/files/7346184/Crashtest.zip)

**Comment by orapps44** [comment]
Hi,

I'm not able to reproduce your issue.
I'm using framework 4.6.1
