### ISSUE TITLE
Any luck to support multiple themes per application?

### ISSUE THREAD

**Issue by AhmedSalehz** [leocb/MaterialSkin#25]
I understand that the whole concept is to provide a consistent app theme, however i only need to have some forms in Light and the others in Dark!

Any workaround for this?

Thanks,

**Comment by leocb** [comment]
Hi. Currently this is not supported and would break some principles of the Material Design about consistency, So I'm not planning to support it anytime in the future.

Some details:

The current system uses a single `SkinManager` instance for the whole app, making it very easy to keep the interface consistent without having to write boilerplate code for every form/control

If you want to do it yourself, the first step would be to make the `SkinManager` constructor public, remove the `Instance` method (breaking EVERYTHING) then create and save a  `SkinManager` instance on the `MaterialForm` and then, on every Control, use a cast on the `FindForm` method to find the `MaterialForm` instance for the control, and get the SkinManager from it. However, for every form you create, you will have to write the SkinManager boilerplate code for it.

Good luck :)

**Comment by AhmedSalehz** [comment]
Hi Leocb,

Thanks a lot for your prompt response.

I was able to find a solution for my case to define two different themes per application.

First, i recompiled the MaterialSkin assembly with a different namespace 'MaterialSkin2', then i referenced the new materialskin2.dll to my application which gave me the ability to declare two different SkinManagers.

Initial testings went perfect!

Regards,

**Comment by leocb** [comment]
Hmm that's not ideal, if you want to upgrade your materialskin verison, you'll need to repeat this process. Well, if it works for you, why not :)

**Comment by AhmedSalehz** [comment]
Yes, I know :) I will have to recompile on each update till the feature get implemented!
