### ISSUE TITLE
Strange position of window when minimize

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#272]
Hi,
If I store form's position and size when I minimize it, then strange values are stored. I think the same thing will happening if I will store the form's position and size if I will maximize form, it will not store the "real" size, or pozition.

![StrangePosition](https://user-images.githubusercontent.com/49796453/139680446-2fc2a4c4-a4f7-41a3-bec7-a4f703c96a86.jpg)

I think the values of `Top`, `Left`, `Width`, `Height`, must be the values before `Maximize`/`Minimize` action. So, could you do something to store those values?!
As a workaround, I will check for what I will do with form before saving position and size. If it is `Minimized`, I will not save `Top` and `Left`, and if it is `Maximized`, I will not save the values of `Width` and `Height`. I must preserve those values as they are before.

**Comment by VolatilePulse** [comment]
Are you looking for the `Rectangle` provided by [RestoreBounds](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.restorebounds). It's unusual to obtain the location of a form when it is minimized. How are you obtaining those values? When are you obtaining those values?

**Comment by valimaties** [comment]
> Are you looking for the `Rectangle` provided by [RestoreBounds](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.restorebounds). It's unusual to obtain the location of a form when it is minimized. How are you obtaining those values? When are you obtaining those values?

Hi @VolatilePulse,
IMO, the location of form, before minimize or maximize, is the last position known before those actions.

**Comment by VolatilePulse** [comment]
I had another look at this today. [RestoreBounds](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.restorebounds) is designed to store the position of the window, but it is only updated prior to being maximized or minimized. The current location and size can be derived from [Size](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.size) and [Location](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.location). However, minimized windows don't set the location and size like you'd expect. Windows effectively draws the windows off screen. You can check the [WindowState](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.windowstate) to determine which properties you want to record.

If this solution doesn't work, you'll need to explain specifically what you're looking for so I can help provide a better solution.

**Comment by valimaties** [comment]
> ... 
You can check the [WindowState](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.windowstate) to determine which properties you want to record.
> 

Yes, seems that is the solution for my problem, saving window size, location and state.
Thanks!
