### ISSUE TITLE
Maximize form issue

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#277]
Hi,
I working on a PC with 2 monitors, a Philips 243V5 and a BenQ FP222Wa. 
Philips resolution is 1920x1080, 60kHz, 8 bit
Benq resolution is 1680x1050, 59.954Khz, 8 bit.

When I maximize main form on Philips, it is maximizing ok, but on Benq monitor it take somehow the size of Philips, the window is larger than the size of monitor.

**Comment by orapps44** [comment]
Hi @valimaties ,

Yes, I confirm. I'm also using two monitors with different screen resolutions.

**Comment by VolatilePulse** [comment]
Does this issue happen when you use aero snapping to maximize or only when you double click the title bar or click the maximize the button?

**Comment by orapps44** [comment]
It happens in all cases (aero snapping, double click on title bar and maximize button) on second monitor only (smaller screen resolution).
