### ISSUE TITLE
Removing of property AccentTextColor.

### ISSUE THREAD

**Issue by Dolefly** [leocb/MaterialSkin#280]
This property that you removed under "Clean up code and remove unused property AccentTextColor." pull 278, is causing the project to cry though it is unused, it was created automatically on the earlier version. So if you have a project with more than 100 buttons you will need to comment out or delete this line, for example in my button;
`this.btnDBSettings.AccentTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(64)))), ((int)(((byte)(129)))));`
So the question is should we soldier on and delete or comment them?

**Comment by valimaties** [comment]
Hi @Dolefly ,
Personally, I deleted those lines of code.

**Comment by orapps44** [comment]
Hi @Dolefly ,

You can comment or delete AccentTextColor property since it has been removed with PR #278.

If you are using light & dark mode it may also be necessary to reset NoAccentTextColor property value for each button. 

```c#
this.btnDBSettings.NoAccentTextColor = System.Drawing.Color.Empty;
```

You can use some advanced text editor with macro to do it faster.
