### ISSUE TITLE
MaterialTextBox2 - issue after switching Enabled property

### ISSUE THREAD

**Issue by mayorovsv** [leocb/MaterialSkin#282]
Hi,
I have faced with an issue with MaterialTextBox2. 

Initially I have MaterialTextBox2 control in **Enabled = true** state, after that I switch it to **Enabled = false** and it works fine. But when I try to switch it back to **Enabled = true** again I face with weird behavior: control not fully enabled after that, i.e. I'm able to click on trailing icon, hover effects start working, but control stucked in kind of readonly mode - the text is grayed out and not editable.

Also I was able to reproduce it on example project.
Could you advice, please?

**Comment by orapps44** [comment]
Hi @mayorovsv ,

Thanks for reporting this issue. 
I confirm the unexpected behaviour. I will work on it and fix it as soon as I can.
