### ISSUE TITLE
Nuget MaterialSkin2 2.3.0 not fully supported in .Net5 solution

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#287]
![NotFullySupported](https://user-images.githubusercontent.com/49796453/140881138-2c82aee4-82db-477e-80fb-0177af4acb1c.jpg)

**Comment by VolatilePulse** [comment]
@orapps44 I didn't even see that you published a NuGet package. How did you build the package?

**Comment by orapps44** [comment]
Package was build using 'nuget pack' command.

I ve tried to make a new package but didn't succeed to update .nuspec file correctely to integrate dll for net5.0. neither to create package from MaterialSkinCore.csproj.
Could you advise me what command should I use to create proper nuget package ?

**Comment by valimaties** [comment]
In VS 2019 (2022) there is a Pack command when you right click on project.
Attached is bin folder created by me using `Pack` option in contextual menu of my VS2022 installation. The location of bin folder is in `MaterialSkin` folder
![Location](https://user-images.githubusercontent.com/49796453/141111897-e6a43ba4-e3c8-4306-b182-f19720357b63.png)


[bin.zip](https://github.com/leocb/MaterialSkin/files/7512592/bin.zip)

**Comment by valimaties** [comment]
Hi @orapps44  
Did you used bin folder generated?

**Comment by orapps44** [comment]
> simply right clicking on the Core project and selecting `Pack` will create a NuGet package for you that is already multi-targeted.
> 

Thank you, I did release new multi-targeted package version 2.3.1 on nuget.
