### ISSUE TITLE
FlowLayoutPanel background color

### ISSUE THREAD

**Issue by goto3** [leocb/MaterialSkin#29]
Hello, can not set my FlowLayoutPanel background color to any color, not even transparent:

![image](https://user-images.githubusercontent.com/16456164/68266947-64091080-002f-11ea-9832-50e2218dd3ee.png)

in the designer it changes the color but when I compile the program the background color wont change.

I am using latest version of MaterialSkin and .NET 3.5
What should I try? 

Thanks

**Comment by goto3** [comment]
Line 183 in MaterialSkinManager:

![image](https://user-images.githubusercontent.com/16456164/68267530-7dab5780-0031-11ea-82c0-e202fb8cef6e.png)

if I change that color, al panels changes background. Is there a way to disable that feature?

**Comment by leocb** [comment]
Hi. The manager enforces the background color on components. I supposed I could leave that as a flag that can be disabled by the user.
If you're compiling the lib yourself, do this:

On the file `materialSkinManager.cs` in the function `UpdateControlBackColor` comment the last `else if` block. This should stop the manager from updating controls that are not part of the materialSkin lib.

But bear in mind that now you'll have to update by hand the backcolor of all non-material componenets, this specially breaks dark themes.

Happy coding ;)

**Comment by goto3** [comment]
:O thank you very much sir

**Comment by leocb** [comment]
This now has a wiki entry [here](https://github.com/leocb/MaterialSkin/wiki/FAQ#backcolor-property-on-non-material-components)
