### ISSUE TITLE
MaterialButton Icon position issue when AutoSize is false

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#296]
Hi. There's an issue with position of `Icon` on MaterialButton, when `AutoSize = false` and the `Height` of MaterialButton is greater than default.

Demo:
![ButtonIconPositionAndOverlayIssue](https://user-images.githubusercontent.com/49796453/141450653-faa9f20c-bf5b-49ca-bfdf-b8febc607acb.gif)

**Comment by orapps44** [comment]
You're not supposed to modify material button height.
I would suggest to keep ```AutoSize = true``` to keep compliancy with material design specification.

**Comment by valimaties** [comment]
I thought MaterialSkin is based on Material Design, but not necessary use all the restrictions of Material Design. In some circumstances, when there is a lot of text but the width of button's parent container does not allow a long button, to let Material Skin choose the width of my button, I must wrap text inside button. Which means that the height of this button it must be other than restricted one by Material Design specification. And they don't restrict, they only suggest not to wrap!
If the user don't have the "freedom of choice", in most of the cases they will search for another "skin" pack.
Yes, I agree that "default" use/layout of a control must be `Material Design`'s implementation and _suggests_. But MaterialSkin could do other thing over the _based_ implementation (I think...)
