### ISSUE TITLE
MaterialTextBox form freeze

### ISSUE THREAD

**Issue by techmatikdev** [leocb/MaterialSkin#307]
Hi, firstable I'd like to thank all the great people working on this project, it's the best thing thath could happen to the wooden Windows Forms. I've been waiting for a long time for the latest updates to the package but I found an issue that blocks me with updating my app's release version. 

Scenario:

Create project with MaterialSkin2 (v 2.2.1). Create two forms, first can have only one button to open second form with MaterialTextBox and MaterialButton. On that form you can just for the test prupose read MaterialTextBox's value to the variable and Close form to return the parent one. Check if everything works fine then update MaterialSkin2 to the newest version and see what's going to happen.

With version 2.2.1 everything except the MaterialTextBox cursor works fine.
With version 2.3.1 MaterialTextBox works great but when you click on the button on the form with MaterialTextBox app hangs.

Thanks and once again congrats to all people involved in this project.
Paweł

**Comment by valimaties** [comment]
Yes, this is a known bug for `MaterialTextBox` control. Use `MaterialTextBox2` instead. This has solved my problems.

**Comment by silaros88** [comment]
Ok great I'm going to check that in the evening, thanks in advance

**Comment by valimaties** [comment]
@techmatikdev and @silaros88 , please confirm that `MaterialTextBox2` solved your issue and if so, close this issue.

Regards,
Vali

**Comment by silaros88** [comment]
Hi I checked that yesterday and on MaterialTextBox2 everything works as expected. So I think that next version of the library should have removed old MaterialTextBox and it should be replaced with MaterialTextBox2.

Thanks once again

**Comment by valimaties** [comment]
I expect also that `MaterialTextBox` to be at least marked as `Obsolete`.
Ok, @orapps44 or @techmatikdev , please you can close this issue 👌.
