### ISSUE TITLE
How to change fonts

### ISSUE THREAD

**Issue by yosi90** [leocb/MaterialSkin#315]
I need to change one control font size, but i read that fonts are hardcoded, that we must use the type scale, but.. how do i do this?
the reference that you gave in #166 isnt for c#.
how do i change font size or type scale in c#?

**Comment by orapps44** [comment]
Hi, 

If you want to change font size of one of MaterialSkin controls, #166 suggest to create your own fork and change font size directely in `MaterialSkinManager.cs` , but this will apply to all controls.
