### ISSUE TITLE
Icon support in tab selector

### ISSUE THREAD

**Issue by Serraniel** [leocb/MaterialSkin#319]
I wanted to use the tabselector with icons in the tab sheets. So I tried to set them up similar as it is working for the drawer: 
* Assigned Imagelist to the material tab control
* Assigned ImageKey to the tab sheet
* Assigned tab control to the tab selector

But the tab selector only displays the name, not the icon:
![image](https://user-images.githubusercontent.com/8461282/147886903-028fbe0f-96bb-4b93-89bf-f5470d85ad53.png)

**Comment by valimaties** [comment]
`TabSelector` control can accept icons, by setting the `Tab Label` property of `TabSelector` to `IconAndText` but I see an issue with the Height of it, which will not change the position of `TabControl`. Maybe another approach, by adding a new enumeration property to `TabSelector` which must positioning the icon to the left/right/up/down of label is better than this fix position of top/up. Personally, I don't like it as it is now. And I think that icons must be recolored as they are colored in drawer.

![TabSelector icons](https://user-images.githubusercontent.com/49796453/147922603-992231f1-7c28-434a-a23b-e6ea5398aa77.png)

**Comment by orapps44** [comment]
> I don't like it as it is now. And I think that icons must be recolored as they are colored in drawer.

I agree it could be improved.

**Comment by Serraniel** [comment]
Thanks for your reply. Must have overseeh the property.
