### ISSUE TITLE
No UserControl support

### ISSUE THREAD

**Issue by ExoKalork** [leocb/MaterialSkin#320]
Is there any plan to support UserControl in the future ?
Right now, when trying to add a UserControl to my form, because the controls don't like a transparent background, they make a black background instead, which obviously breaks the theme.

**Comment by valimaties** [comment]
Hi @ExoKalork 
As I know, writing the code below to your UserControl will set its background as transparent:

```cs
protected override CreateParams CreateParams
{
    get
    {
        CreateParams cp = base.CreateParams;
        cp.ExStyle |= 0x20;
        return cp;
    }
}
```

Example of a `Test` UserControl:
`Test.cs`
```cs
public partial class Test : UserControl
    {
        public Test()
        {
            InitializeComponent();
        }

        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams cp = base.CreateParams;
                cp.ExStyle |= 0x20;
                return cp;
            }
        }
    }
```

**Comment by ExoKalork** [comment]
Oh this indeed looks right, thanks a lot !
