### ISSUE TITLE
Change height of textbox

### ISSUE THREAD

**Issue by puremoco** [leocb/MaterialSkin#323]
Hello together,

I am currently trying to implement the MaterialSkin into my project and noticed, that it is not possible to change the height of the TextBox. It is fixed to 48px no matter what I try.

It takes al lot of space which I need.

Is there a workaround to get a smaller textbox?

<img width="191" alt="aa" src="https://user-images.githubusercontent.com/10936758/148676843-b00545ab-75ef-4327-b866-182719281a21.PNG">

**Comment by orapps44** [comment]
Hello,

Yes, this is normal behaviour to match Material Design spec.
You can use ```UseTallSize``` property to false to make control smaller (36px instead of 48px).
