### ISSUE TITLE
TextBox Issue

### ISSUE THREAD

**Issue by RedDot-3ND7355** [leocb/MaterialSkin#324]
When closing a child form that has a or more textboxes. (That is filled- non empty)
The process hangs. And then forced to close the app via taskmanager.

The mainthread is probably locked due to this.

The solution I had to resort to was to empty the text fields and then close the child form.

**Comment by orapps44** [comment]
Hi,

Does it happens when using `MaterialTextBox` or `MaterialTextBox2` control ?
If you are using `MaterialTextBox` I suggest you to replace it by `MaterialTextBox2` control.

**Comment by RedDot-3ND7355** [comment]
> 

Yes, I'll try switching the controls to MaterialTextBox2 instead. I'll give you an update if it fixes it! :)

**Comment by valimaties** [comment]
@RedDot-3ND7355 , this issue can be closed?

**Comment by byungmeo** [comment]
i think Password attribute is problem
https://github.com/IgnaceMaes/MaterialSkin/issues/272

**Comment by MartinErdely** [comment]
The issue is caused if the Password attribute is true and the control contains text when form gets closed. Can be resolved by clearing textbox text on form close event.

**Comment by RedDot-3ND7355** [comment]
Password attribute was indeed the issue!
