### ISSUE TITLE
MaterialTextBox2 number letter space is worng

### ISSUE THREAD

**Issue by Quekie** [leocb/MaterialSkin#326]
![QQ截图20220115205016](https://user-images.githubusercontent.com/13919102/149622326-83d8882e-f22b-40f4-b660-8e4d3e71514c.png)

**Comment by valimaties** [comment]
Hi @Quekie .
Can you tell us what are your conditions of graphics? I wasn't able to reproduce this issue.
Can you make a small app and reproduce this issue in this new app?
Please upload it here, if so..

Regards,
Vali

**Comment by Quekie** [comment]
OMG , The problem gone when i look it again , i can't reproduce it. This happends after i upgrade MaterialTextBox to MaterialTextBox2 .

**Comment by Quekie** [comment]
Thank u , i will close issue for now, when i find it again i will open issue again

**Comment by valimaties** [comment]
Yes, MaterialTextBox is deprecated. MaterialTextBox2 is the current control to use as a textbox control.
