### ISSUE TITLE
Form does not allow animation from WindowFX

### ISSUE THREAD

**Issue by firepacket** [leocb/MaterialSkin#343]
The software [Stardock WindowFX](https://www.stardock.com/products/windowfx/) causes all windows to become animated while moving, opening, closing, and sliding while also adjusting transparency based on focus.

MaterialSkin forms do not allow this animation, so on my system while all other applications move and slide around nicely, the MaterialSkin form is ridged, does not slide, does not animate, does not change transparency, and does not fit with all the other applications running on my system!

Does anyone know how this can be fixed?

**Comment by valimaties** [comment]
I don't think something must be fixed... 
This is Material Skin and it has to be like this! This "theme" has it's own build-in animation manager for controls, and follows the principle of Google's Material Design.

**Comment by firepacket** [comment]
Right but does it run on Android or Windows? Should it not behave the same as other windows on a Windows operating system?

**Comment by valimaties** [comment]
No, because the windows are rewritten! Some of the base init functions it works only for some conditions.
If you want to make work that application, I don't think it will work with MaterialSkin!
If you find a solution, please feel free to create a PR.

Regards,
Vali
