### ISSUE TITLE
Combobox text property Not Working

### ISSUE THREAD

**Issue by talhayksk** [leocb/MaterialSkin#348]
hello, I want to add data to Combobox text property but I can't set it. **(materialCombobox1.Text="example")** this method doesn't work.

**Comment by valimaties** [comment]
I suggest using `List<string>` as `DataSource` for your `MaterialCombobox` object. Then use `SelectedValue` to get its value, but check that its `SelectedIndex` value to be greater than -1, else the value is `string.Empty`.

``` cs
private List<string> CmbDataSource;
private string ComboSelectedValue { get; set; }

// your other code
// This method you will call in your class constructor, or anywhere else
private void SetComboboxDataSource()
{
    CmbDataSource = new List<string>();
    CmbDataSource.Add("Some First Value");
    CmbDataSource.Add("Some Second Value");
    CmbMaterialCombobox.DataSource = CmbDataSource;
}

// Other code here

private void CmbMaterialCombobox_SelectedIndexChanged(object sender, EventArgs e)
{
    if (CmbMaterialCombobox.SelectedIndex == -1)
    {
        ComboSelectedValue = string.Empty;
        return;
    }
    ComboSelectedValue = CmbMaterialCombobox.SelectedValue.ToString();
    // here you can do other things with this selected value
}
```

PS: I'm not on a computer with VS, so I didn't test this code, I hope it is written well 🙂

**Comment by talhayksk** [comment]
thank you,
I'm already loading it this way, but then I want the name field to appear from the row with the combobox text set selected in the DataGridView cells_click event, but it doesn't set.
```
      public static async Task Parti(ComboBox comboBox)
        {
            var data= await _employee.GetAll();
            data.Insert(0, new Employee{ Name= "Select", Id = 0 });
            comboBox.DataSource = data;
            comboBox.DisplayMember = "Name";
            comboBox.ValueMember = "Id";

        }
```
I do it this way, I tried other methods, but I didn't get the request.
textbox also happens with this method

```
        private void datagridView_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            matCombobox.Text =datagridView.CurrentRow.Cells[2].Value.ToString();
          
   
        }
```

**Comment by valimaties** [comment]
Your DisplayMember cannot be Name, because Name is a property of Employee class. Try set DisplayMember = "Employee.Name" and ValueMember = "Employee.Id".

**Comment by valimaties** [comment]
And, BTW, I made some tests now, and `Text` property works...

![MaterialComboboxTextProperty](https://user-images.githubusercontent.com/49796453/159927073-ffc7ef02-fe87-4801-b9ba-24974115dbea.gif)

**Comment by valimaties** [comment]
@talhayksk , some news about this issue? Did you managed to make it work on your side? If so, you may close this issue.

**Comment by valimaties** [comment]
I will make some tests on my side with datagridview and I will come back with a feedback.

**Comment by talhayksk** [comment]
Thank you very much for your attention. I will be waiting

**Comment by talhayksk** [comment]
Hi @valimaties , first of all, I'm sorry, I couldn't get back to you because of the issues that developed out of my will for a long time. I solved the problem in line with the information you gave, thank you, in this case, we can close this issue.
