### ISSUE TITLE
Styling the border of the Combobox dropdown

### ISSUE THREAD

**Issue by progmars** [leocb/MaterialSkin#363]
Currently combobox dropdown part shows default border (blueish for me on Windows 10).

It turned out it's very tricky to style it but I found a working implementation on StackOverflow: https://stackoverflow.com/a/24307439/217823

It's ugly and hacky but it gets the thing done. Maybe it's worth considering to be integrated into MaterialSkin?

**Comment by orapps44** [comment]
Hi,

See #153
