### ISSUE TITLE
Switch has error when making changes to database and reloading in winform c#

### ISSUE THREAD

**Issue by Doannguyen1996** [leocb/MaterialSkin#367]
I make changes in the database, affecting the lable content when checking or unchecking the switch for example when the check lable is "yes", when unchecking the label content will be "no", After I update to the database, it will reload the data, but the default display switch is checked and cannot be changed, I have tried many times, although when I click on it, the lable content still changes, but the switch interface it doesn't change at all, I think this is a bug from this skin

**Comment by valimaties** [comment]
Put some code to see what you are doing.

**Comment by valimaties** [comment]
I've made a little project trying to achieve your issue, but mine works well... Supposing my listbox contains your DataBase values, the switch changes its status from checked to unchecked and viceversa depending on the value of the selected item's text.
Look here:

![SwitchExample](https://user-images.githubusercontent.com/49796453/189659032-53a5e660-efd5-49ac-a24a-c8628b3a3fc3.gif)

**Comment by Doannguyen1996** [comment]
thank you! i done!

**Comment by valimaties** [comment]
If this issue is solved, please close it 🤗.
