### ISSUE TITLE
Modify border style for drop shadow

### ISSUE THREAD

**Issue by ryanrox** [leocb/MaterialSkin#375]
The material forms don't have a background drop shadow like a normal windows form or dialog box does. Has anyone had any issues with this or know how to replicate this border style? I've tried changing the border style of the form and tested code on the MaterialForm control but no luck.

![test](https://user-images.githubusercontent.com/84647797/203168144-5c75b9d6-5665-4aa7-a37a-2bc6c3c25dd4.png)

**Comment by leocb** [comment]
That's a limitation of windows forms and can't be fixed
