### ISSUE TITLE
Can't Use Tools/Controls

### ISSUE THREAD

**Issue by EmanDev** [leocb/MaterialSkin#38]
Can't use 'some' tools/controls from the reference MaterialSkin

I'm creating a project with C# targeting .NET Framework 4.7 on Visual Studio 2015.
I have included this much on my project.

using MaterialSkin;
using MaterialSkin.Controls;

public partial class Form1 : MaterialForm

var materialSkinManager = MaterialSkinManager.Instance;
materialSkinManager.AddFormToManage(this);
materialSkinManager.Theme = MaterialSkinManager.Themes.DARK;
materialSkinManager.ColorScheme = new ColorScheme(Primary.BlueGrey800, Primary.BlueGrey900, Primary.BlueGrey500, Accent.LightBlue200, TextShade.WHITE);

Tried dragging/double click controls in the toolbox to be included in the form.
What works:
Material Label
" radio button
" tab selector
" progress bar
" divider

**Comment by leocb** [comment]
Hi, thanks for reporting.

Could you be more specific on what doesn't work and what errors you get?

**Comment by EmanDev** [comment]
Hi sorry for this opened issue, seems like its my fault for not paying enough attention to details.
Everything is working correctly now, I kinda mess around on using the controls.

**Comment by leocb** [comment]
No problem ;)
Although I'm curious on how you could create errors for just messing around with the controls, is it something I could prevent on the materialSkin side? Part of my objectives is to make this lib as simple to use as possible
