### ISSUE TITLE
Tooltip for Tabpages

### ISSUE THREAD

**Issue by TjeuSijtsema** [leocb/MaterialSkin#394]
Hi there, first off i am absolutely loving this nuget package! it makes it super easy to make a slick looking app.
the issue im having is that i would like to add tooltips to the tabpages. 
When i try to do this in the property manager they wont show up. Also tried it by putting:
 {tabname}.ToolTipText = "Tooltip Tabpage Test";  in the designer.cs

but for some reason the tooltip does not want to show when hovering over a tab with the mouse. is there a way i could get this to work?
sincerely

**Comment by valimaties** [comment]
First of all, you know that this library is marked as obsolete, let's say like this. Is no longer supported.

Second, is not so easy. You have to make it yourself, by modifying MaterialTabSelector. You  can add a Tooltip object in this control and change its text in OnMouseMove event for each tabs in selector.

**Comment by TjeuSijtsema** [comment]
tyvm Vali, 

i did see that this project is no longer supported. and ive also given this information to the head of the project. i will give this a go at least see if i can make it work but nonetheless tyvm for answering the question :)
