### ISSUE TITLE
Card doesn't appear properly when instanciated from code

### ISSUE THREAD

**Issue by ThibaudMZN** [leocb/MaterialSkin#41]
If you instantiate Cards from any event in your code, the actual display seems to be way off, any ideas why ?

`
MaterialCard card = new MaterialCard();
card.Margin = new System.Windows.Forms.Padding(14);
card.MouseState = MaterialSkin.MouseState.HOVER;
card.Padding = new System.Windows.Forms.Padding(14);
card.Size = new System.Drawing.Size(200, 100);

flowLayoutPanel1.Controls.Add(card);
`

AS you can see, the first card is instantiated in design mode, looks fine, but the 3 others look weird.

![Capture](https://user-images.githubusercontent.com/1643465/72365454-435fd580-36c6-11ea-9254-b8735208b392.PNG)

**Comment by leocb** [comment]
Thanks for reporting! I was able to replicate the behavior you described, and it seems to be related with the issue #14. I don't know the specifics with flowLayoutPanel, but it seems it removes and re-add the control when moving them (?) either that or the paint event for it is firing at the wrong order , before the cards, so the position and size is wrong. The GDI manages this, so I don't know a imediate solution. I'm upping the priority on that issue as this can be breaking on other scenarios. 

Also, this can be replicated with any control that casts a shadow on the parent, such as the Material Button or FAB.

This is my result after resizing the screen, as you can see, the shadows are drawn, but in the wrong locations:
![image](https://user-images.githubusercontent.com/8310271/72382938-1a0c6d00-36f9-11ea-8bee-f6340fb016b1.png)

**Comment by ThibaudMZN** [comment]
I also managed to make it work by manually calling Refresh() after adding the cards on the form, but surely it's not the most elegant way.

**Comment by leocb** [comment]
Yeah, refresh invalidates the control and forces a complete redraw. You can use this for the time being, but it's slow, I'll try to fix this asap

**Comment by leocb** [comment]
Hey @ThibaudMZN , try the latest version from master (you'll have to compile it yourself, just add the csproj to your solution and add the internal reference).
If everything is working correctly, I'll push a release and a new version of the MaterialSkin.2 to nuget

**Comment by leocb** [comment]
hi @ThibaudMZN, I just want to confirm if this resolved your issue? thanks

**Comment by ThibaudMZN** [comment]
I didn’t tested yet, I’ll do it this next days and let you know !

**Comment by ThibaudMZN** [comment]
@leocb problem solved with latest update 2.1.1, Thanks !
