### ISSUE TITLE
Icons Appear Pixelated

### ISSUE THREAD

**Issue by bdizzleog** [leocb/MaterialSkin#42]
I added icons, but they are very blocky. Is there a solution to this?

![image](https://user-images.githubusercontent.com/23192833/72385593-dceead80-36ed-11ea-8300-1d3969a10176.png)

**Comment by leocb** [comment]
These looks like a resolution scaling artifacts. Try changing the scaling mode on the imageList control, also, what resolution are you using? The recommended is 24x24 png - see the resources folder on the example app, those icon are taken from Google at 24dp, color doesn't matter, but I recommend black as you can actually see the in the resource explorer on Visual Studio

**Comment by leocb** [comment]
Hi @bdizzleog, did you manage to resolve your issue? thanks

**Comment by filad** [comment]
Go to your ImageList -> ColorDepth -> change it to 'Depth32Bit'.
