### ISSUE TITLE
Card UI Shadow sisible when the card is not visible

### ISSUE THREAD

**Issue by KhrysusDev** [leocb/MaterialSkin#46]
When you make the material card invisible, the shadow is left behind when you open the form. It doesn't disappear when making the card visible and invisible whilst using the form.

**Comment by leocb** [comment]
Hi, thanks for reporting this
Hmm yes, didn't think of that use case 🤦‍♂ 
Will be fixed on the next maintenance (version 2.1.2)

**Comment by leocb** [comment]
Hi @KhrysusDev
Please try the latest version from the master, if everything is ok, then this will be published to nuget on monday
have a nice weekend :)

**Comment by dancoLgh** [comment]
I'm having the same problem. Shadow is not hidden when card.visble = false

**Comment by leocb** [comment]
Hi, could you share the setup you're using when this happens? including the component tree up to the card level? what version of .net?

**Comment by dancoLgh** [comment]
I fixed it, sorry I didn't realize I wasn't inheriting materialForm. Thanks for the work you do

**Comment by leocb** [comment]
np! feel free to open any issues you find!
