### ISSUE TITLE
Cards don't support dark mode?

### ISSUE THREAD

**Issue by KhrysusDev** [leocb/MaterialSkin#49]
When switching to dark mode with a card control, it stays white but glitches all the controls inside it. This is with enforce backcolor with true and false.

**Comment by leocb** [comment]
They do support dark mode, it may be a problem with the component not updating (re-painting) when switching modes. Try calling `materialCard.Refresh()`, if this solves your problem, then it's a bug with the materialSkinManager and I'll have to fix it

**Comment by KhrysusDev** [comment]
Hi,

My program actually doesn't have a option to switch modes, it is just dark mode. And the cards paint in light mode, I still tried to do the refresh and they still painted in white

**Comment by leocb** [comment]
Can you give me some more info on your setup? Mainly the form and materialSkinManager initialization and the card container (example: form -> tab control -> panel -> card)

**Comment by KhrysusDev** [comment]
The materialSkinManager:
`var materialSkinManager = MaterialSkinManager.Instance;
            materialSkinManager.EnforceBackcolorOnAllComponents = false;
            materialSkinManager.Theme = MaterialSkinManager.Themes.DARK;
            materialSkinManager.ColorScheme = new ColorScheme(Primary.Orange800, Primary.Orange900, Primary.Orange500, Accent.Orange400, TextShade.WHITE);`

There is one tab control called TabControl
There is six cards and one panel which is a native WinForms panel
Form is a MaterialForm called MainForm

**Comment by leocb** [comment]
Ok, I'll take a look

**Comment by leocb** [comment]
Hi @KhrysusDev, could you please send me a screenshot of the interface? Both while in the designer and while in runtime. You can blur out sensitive info if needed

**Comment by leocb** [comment]
In the example app it's working correctly with the same initialization you're using (just different colors)
Did you set `materialSkinManager.AddFormToManage(this);` on your form initialization? I don't see it mentioned on your comment - not adding it breaks a lot of things.
![image](https://user-images.githubusercontent.com/8310271/73206323-7623b800-4121-11ea-8b7c-8b939212c702.png)

**Comment by KhrysusDev** [comment]
Hi,

Sorry for the late reply, only saw the message now. Anyways, the code I sent did have the add form to manage code, but I missed it out, and yes I did add it to a panel, and it doesn't have a effect. So I added a dark panel INSIDE the card to make it dark. 

Please see the attached screenshots below
![ss](https://user-images.githubusercontent.com/59972716/73865289-ee356080-483a-11ea-82b2-b44485d127b7.png)

**Comment by leocb** [comment]
No problem, and no time wasted, it's better to investigate the little things than leave bugs lurking around ;)

Feel free to open any issues
