### ISSUE TITLE
Primary text color is indistinct in dark mode

### ISSUE THREAD

**Issue by rydevelop** [leocb/MaterialSkin#5]
I suggest increasing brightness of the primary text color in dark mode to improve visibility.
thanks

![image](https://user-images.githubusercontent.com/30257122/66242270-413bc180-e73c-11e9-8701-71293d844d23.png)

**Comment by leocb** [comment]
I agree, but this is up to the app designer to change, color schemes are configurable at runtime, it's up to the programmer to change the colors together with the theme.
Best I can do is program this behavior on the example app, but hard-codding brighter colors in the materialSkin lib would be confusing for users

**Comment by leocb** [comment]
Oops, not supposed to close this :P
