### ISSUE TITLE
Controls not showing properly when inside a tab control

### ISSUE THREAD

**Issue by ThibaudMZN** [leocb/MaterialSkin#52]
When I'm adding controls to a tab control page, they appear black. I think this behavior was also here in the first version of Material Skin but they somehow fixed it at some point. Any clue on how to fix that ?

![image](https://user-images.githubusercontent.com/1643465/73461382-0ba09100-4348-11ea-83bf-278d3b76a34f.png)

**Comment by leocb** [comment]
Hi, thanks for reporting
This happens only in designer, it happens because the tab backcolor default value is `transparent`, just set it to something else, like white. I'll try to fix this in the next maintenance release.

**Comment by leocb** [comment]
This is a duplicate of #30, but will leave it open so I can fix it

**Comment by TomsDev67** [comment]
I confirm I've also this issue.
Depending the skin, it's working when the application is launched and only having black colors in Visual Studio.
Thanks in advance :)
