### ISSUE TITLE
Can't resize ContextMenuStrip item

### ISSUE THREAD

**Issue by TomsDev67** [leocb/MaterialSkin#54]
Hello,

I'm looking to extend the width of **MaterialContextMenuStrip** items because in my case some texts are too long and they're are cut. I've tried to modify in code some Size properties without effect for now. I was not able to find a good answer in google _(And I'm not sure if it's something about the default ContextMenuStrip component or the overide with Material.Skin)_

If you've any idea, let me know,
Thanks in advance,

See below
![menuSizeIssue](https://user-images.githubusercontent.com/8772453/73645301-54718600-4677-11ea-85f7-1a87c3352865.png)

**Comment by leocb** [comment]
Hi, that's the MaterialDrawer, not ContextStripMenu 😅 
You can resize it by changing the DrawerWidth property on the Form
![image](https://user-images.githubusercontent.com/8310271/73653066-21bf9180-4667-11ea-8da4-e24efa71f80b.png)
