### ISSUE TITLE
Designer not loading Forms inherit from MaterialForm

### ISSUE THREAD

**Issue by TomsDev67** [leocb/MaterialSkin#57]
Hello,

At first I had included MaterialSkin as a project in our solution. I've modified and improved some of our application screen without issues.
But after a build on our server, SonarQube was crying too much, so I've decided to put MaterialSkin as a *.dll in our project.

**Steps I've done :**
- Cloned the Git
- Changed target framework from 4.6.1 to 4.7.2 _(was also the case when MaterialSkin was included as project in our solution)_
- Signed the assembly with a *.pfx
- Compiled as release - AnyCPU
- Created manually a NuGet package including the generated *.dll
- Uploaded on our local NuGet Repository
- Removed the project in our solution and replaced with reference to the NuGet package.

And since this, when I try to load Form having something from MaterialSkin, I've this issue.
`The designer could not be shown for this file because none of the classes within it can be designed. The designer inspected the following classes in the file: MainForm --- The base class 'MaterialSkin.Controls.MaterialForm' could not be loaded. Ensure the assembly has been referenced and that all projects have been built. `

**Call stack :**
```
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.EnsureDocument(IDesignerSerializationManager manager)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.DeferredLoadHandler.Microsoft.VisualStudio.TextManager.Interop.IVsTextBufferDataEvents.OnLoadCompleted(Int32 fReload) 
```
**Any idea ?** I've tried classic things like clean NuGet Repo, Clean project, reboot VS19 (last available version), reboot computer, rebuild, etc.
I've also tried to create a new empty Form and just add inheritance to MaterialForm, the result is the same.
Compiling the project is working fine and launching it is also working, the UI is working well.

**UP :** I've done another test, removing the signing on MaterialSkin. And i've created a new Winform project with a empty Form, added my Nuget Package and inherit it, and it's giving me the same error.

**Comment by leocb** [comment]
Hi, thanks for the detailed report and sorry for the delay, I could've sworn that I replied to this. 😕 

I've never heard of SonarCube before, sounds very usefull. I'll try to fix any issues it reports on this project :)

As for your error, the **call stack** doesn't point to it being an error in the materialSkin lib, I got [this result](https://social.msdn.microsoft.com/Forums/windows/en-US/c9a6d737-b2ab-44fa-880c-e16942c2a979/the-designer-could-not-be-shown?forum=winformsdesigner) on a quick google-fu session, seems like this is a visual studio issue or incompatible .net framework version, MaterialSkin requires 4.6.1 minimum, if you need a older version, try changing it on the project settings.

Honestly, everything i was going to suggest, you said you already tried... sry 😞

**Comment by TomsDev67** [comment]
Hey, thanks for your reply :)

In some articles and forums, they're talking about NuGet issues but I've a good news, I've changed how I'm creating my NuGet Package and now it is working fine !

At first, I've based my package on this one :
![sdkShim](https://user-images.githubusercontent.com/8772453/75659731-c1723e80-5c6a-11ea-9330-28c25f6b1fec.PNG)

And now it is like this :
![MatDesign](https://user-images.githubusercontent.com/8772453/75659736-c3d49880-5c6a-11ea-8672-5b2f135ff4b5.PNG)

**Comment by leocb** [comment]
Glad you got it working, feel free to open any new issues :)
