### ISSUE TITLE
It's coolest when ROBOTO is applied to ComboBox fonts!

### ISSUE THREAD

**Issue by rydevelop** [leocb/MaterialSkin#6]
thanks

![image](https://user-images.githubusercontent.com/30257122/66243266-eb1c4d80-e73e-11e9-8eb7-e6ee9bcfa599.png)

**Comment by leocb** [comment]
Combobox is the next control I'll improve, material theming on the combo dropdown is not "required" per material design standards, a combobox with it is called an "Improved dropdown"
Thanks for reporting, I'll take a stab at it.

**Comment by leocb** [comment]
Solved on commit c1ebd8c3d5b6a2b8ec26cda99c04d8fa3564c8d2 (accidently pushed directly to master, so no PR) will be available on next release
