### ISSUE TITLE
Chart isn't being shown correctly under MaterialTabPage

### ISSUE THREAD

**Issue by Zorono** [leocb/MaterialSkin#62]
Chart isn't being shown correctly under MaterialTabPage...

Expected to be:
![expected_chart](https://user-images.githubusercontent.com/19735243/75182568-5d6ee800-5749-11ea-9288-4b64382ae7d4.PNG)

Current result:
![current_chart](https://user-images.githubusercontent.com/19735243/75182682-914a0d80-5749-11ea-8903-75dd6b95e2cf.PNG)

**Comment by Zorono** [comment]
and the same happens for PictureBox...

**Comment by leocb** [comment]
Try disabling the skin manager enforcebackcolor on the form constructor code. If that fixes this, then try adding and expection for enforcing background color on charts and pictureboxes on the skin manager. You may even open a PR, if you want to :)

**Comment by Zorono** [comment]
No, that didn't solve it...

of course i 'd love to...

**Comment by leocb** [comment]
I'll take a look when I have time, maybe something we do with the window messages to hide the tabs are affecting the chart and pb, but it still could be something else

**Comment by leocb** [comment]
Hi @Zorono, I can't replicate this bug on my side, see:
![image](https://user-images.githubusercontent.com/8310271/76525054-e83e2b00-6449-11ea-9f80-efcb105b23b7.png)

Could you share a example code where this is not working? thanks 😃

**Comment by leocb** [comment]
Closing this as I can't repro it. feel free to re-open
