### ISSUE TITLE
Unknown error when creating MaterialSingleLineTextField under MaterialTabPage

### ISSUE THREAD

**Issue by Zorono** [leocb/MaterialSkin#63]
![ScreenShot_20200224201954](https://user-images.githubusercontent.com/19735243/75183099-71671980-574a-11ea-97b4-0ed1b45a080e.png)

**Comment by leocb** [comment]
That seems like a visual studio error. I see you're on the express 2013 version, Could you try using the 2019 version and report if the problem persists?

**Comment by leocb** [comment]
@Zorono I received some reports on the lib behaving weirdly on some versions of the .net framework, which version are you using? If possible, try version 4.6.2

**Comment by leocb** [comment]
Closing it for now, feel free to re-open if get more info on this
