### ISSUE TITLE
Possibility to add autocomplete on single line textbox ?

### ISSUE THREAD

**Issue by Katalijst** [leocb/MaterialSkin#64]
Hello,
On the vanilla textbox I used to set autocomplete, but now that I switched my app to MaterialSkin I can't do that anymore, is there a possibility to add it back ?

Thanks for your time

Edit:
I just found out this controller is made of the RichTextBox, it cannot be made of the regular TextBox to add the feature ?

**Comment by leocb** [comment]
Hi, sadly, it can't. the normal textbox is missing some features I use to create the material one. Maybe try this? http://forum.codecall.net/topic/55750-c-tutorial-creating-a-auto-completing-richtextbox/

**Comment by orapps44** [comment]
It has just been added in MaterialTextBox2 control.
