### ISSUE TITLE
Double arrow showing in corner top right

### ISSUE THREAD

**Issue by TomsDev67** [leocb/MaterialSkin#68]
Hello,

Sometimes I can see 2 arrow like a little scrollbar in corner top right in my windows and when you resize your screen for example to made it bigger only its appearing>removing>appearing>removing>etc etc
![douleArrow](https://user-images.githubusercontent.com/8772453/76510823-846c3000-6452-11ea-848d-4d5b2e9e94b0.PNG)

I've tried to change some properties without results for now. Maybe someone have an idea to remove them definitely ? :)

PS : If I try to click on them or interact in any way, nothing happen

**Comment by leocb** [comment]
Thanks for reporting! That happens when the tab titles are large enough to cause horizontal scrolling, even tough the tabs are hidden, this thing appears when the width is not enough. It's been in my backlog of bugs, if you can, search the available window messages on google, one of them should hide this... maybe

**Comment by TomsDev67** [comment]
I came to the same conclusion by doing a few more tests. And from what I see it is not possible to access a scrollbar from the TabControl component.

I was not able to find an hack for now 😋

**Comment by leocb** [comment]
Maybe try setting the `Multiline` property of the tab control to `true`, this may break it a lot or not at all 😜

**Comment by TomsDev67** [comment]
Haha great idea !
Really nice workaround ! It's working well on my side. Nothing is broken as I can see. Thanks 👍

**Comment by leocb** [comment]
That's great! If you're sure this isn't breaking anything, maybe open a PR with this fix?
