### ISSUE TITLE
Redesign message box

### ISSUE THREAD

**Issue by leocb** [leocb/MaterialSkin#71]
Inspired by the work done by [spozt/BMS2MB](https://github.com/spozt/BMS2MB) I believe the message box could be a lot better.

inspiration: 
![image](https://user-images.githubusercontent.com/8310271/76766649-1340bb80-6777-11ea-92a1-b1b866ba9beb.png)

I really like how Atlassian considers this UI pattern:

> Use modal dialogs when you need a user response, to reveal critical information, or to show info without losing the overall context of a page. No other interactions on the main page can be accessed while a modal dialog is active. Modal dialogs are invasive to the user's workflow as they appear above all other content. Their usage is quite powerful, as it focuses the user on a single task. -- Atlassian Design System - Modals.

notes:
- The form overlay should be called and should fade the content bellow
- Support for icons
- Support progress bars? [this was deprecated by google](https://developer.android.com/reference/android/app/ProgressDialog), so should we do it?
- Support for user created modals (not required)
- The shadow beneath the modal, even tough it's nice, won't be feasible on widows forms with GDI (maybe migrating to Google Skia should be done at some point? See #37).

**Comment by orapps44** [comment]
PR #222 introduce MaterialDialog control which will cover this.
Result isn't graphically as good as upper example but it will provide a good first control release.
