### ISSUE TITLE
Amazing UI showoff thread!

### ISSUE THREAD

**Issue by leocb** [leocb/MaterialSkin#72]
Have a nice interface you want to showoff to the internet? Post it here!

As always, be careful with sensitive data.

Happy Codding 😉

**Comment by jbradleyisland** [comment]
![Home](https://user-images.githubusercontent.com/62769925/89674303-e8860980-d8b5-11ea-94b2-e53fb8df8b57.PNG)
![Home2](https://user-images.githubusercontent.com/62769925/89674305-e91ea000-d8b5-11ea-8c47-46ac80892e49.PNG)

**Comment by Stefangansevles** [comment]
![image](https://user-images.githubusercontent.com/25766371/93368866-d69d6c00-f84e-11ea-82a4-999a3ed0a54e.png)
