### ISSUE TITLE
ComboBox problem

### ISSUE THREAD

**Issue by lowlevel60** [leocb/MaterialSkin#73]
When I open the MaterialComboBox during runtime and hoover over the text items I get the following result:

![ComboBox](https://user-images.githubusercontent.com/62519888/77259026-ddbc3680-6c7e-11ea-90ac-f7b8384fc68e.png)

When I change the function NativeText.DrawTransparentText in CustomDrawItem in MaterialComboBox to NativeText.DrawString this doesn't happen. But then you would loose functionality, which you don't want. So something is going wrong in NativeText.DrawTransparentText.

Regards,
Rob

**Comment by leocb** [comment]
Hi! Thanks a lot for figuring it out, this is what #60 reported. I'll take a look when I can, but it's hard for me because I can't reproduce this. It may have something to do with dirty buffers

**Comment by lowlevel60** [comment]
I encountered the problem only when the theme was LIGHT in DARK everything looks ok. But I changed the NativeText.DrawTransparentText call in the function CustomDrawItem (MaterialComboBox.cs) with the code below. I don't see the need why this should be drawn with transparent text, so I leave it like this.

using (NativeTextRenderer NativeText = new NativeTextRenderer(g))
{
	NativeText.DrawString(
	Text,
	SkinManager.getFontByType(MaterialSkinManager.fontType.Subtitle1),
	SkinManager.TextHighEmphasisColor,
	new Rectangle(
		new Point(e.Bounds.Location.X + SkinManager.FORM_PADDING, e.Bounds.Location.Y),
		new Size(e.Bounds.Size.Width - SkinManager.FORM_PADDING * 2, e.Bounds.Size.Height)),
	NativeTextRenderer.TextFormatFlags.SingleLine | NativeTextRenderer.TextFormatFlags.VCenter);
}

Maybe, when I have the time, I dive deeper in the GDI calls to see what is causing this. For now it is working for me, thanks.

Rob

**Comment by leocb** [comment]
Thanks for reporting, the transparent is just for getting the correct text color

**Comment by gabigtr5** [comment]
In MaterialSkinManager.cs , increase value of Alfa.

private static readonly Color TEXT_HIGH_EMPHASIS_LIGHT = Color.FromArgb(255, 255, 255, 255); // Alpha 100%
private static readonly Color TEXT_HIGH_EMPHASIS_DARK = Color.FromArgb(255, 0, 0, 0); // Alpha 100%

![screen](https://user-images.githubusercontent.com/33687308/90434727-983d5180-e0d6-11ea-8862-d8cf33153b41.png)

**Comment by lowlevel60** [comment]
Thanks for the fix Stefan.

 

Regards,

Rob

**Comment by leocb** [comment]
While this does fix the issue, it's not ideal as per Material Design principles, The slightly less alpha is to achieve the correct text color (slight grey-ish), and to do that, the text should be drawn with less alpha instead of less rgb values, as seem here https://material.io/design/color/text-legibility.html#text-backgrounds
That's why this text (and every other on this lib) has a alpha value.
feel free to use this fix tho 😃

**Comment by Pacifiquateure** [comment]
Hi, isn't there some way to fix this problem otherwise? Because it is really annoying.

**Comment by leocb** [comment]
Saddly I haven't been able to replicate this bug on my end, hence I can't fix it. I guess this has something to do with dirty buffers when drawing text with transparency. If someone can find a way to replicate this consistently, please leave a comment!
