### ISSUE TITLE
form.showdialog doesn't work properly

### ISSUE THREAD

**Issue by AriVenuth** [leocb/MaterialSkin#78]
When closing a form that was opened as a dialog, some return values ​​do not work.

![image](https://user-images.githubusercontent.com/35943538/79402665-edb7f500-7f62-11ea-8d7d-dc41c0b3d20e.png)

![image](https://user-images.githubusercontent.com/35943538/79403010-ff4dcc80-7f63-11ea-9990-b46b90158b11.png)

![image](https://user-images.githubusercontent.com/35943538/79403331-03c6b500-7f65-11ea-8513-b4f1cf1cc04c.png)

**Comment by leocb** [comment]
Hi, thanks for reporting
This was noted in #67 so I'm marking it as duplicate

It's a incompatibility between .NET 4.6.1 and 4.7.2, I don't know what causes it and the only known solution, if you can, is to downgrade your project to 4.6.1 (same version as the Material Skin Lib)

If you can do some tests, try to clone this repo, add the project to your solution, set it as the materialSkin reference, set it's version to 4.7.2 and then try again. If this works and doesn't break anything, I'll consider updating the lib.
