### ISSUE TITLE
No way to change MaterialTextBox background color

### ISSUE THREAD

**Issue by ThibaudMZN** [leocb/MaterialSkin#82]
I'm struggling to change background color on MaterialTextBox, is the color overriden somewhere ?

**Comment by leocb** [comment]
Hi, custom background or foreground colors are not supported, the colors are enforced by the lib to keep the UI consistent across the whole app. If you're trying to represent an error (such as a required field in a form) this is a requested feature in issue #77.

**Comment by ThibaudMZN** [comment]
Thanks I'll keep an eye on this one !
