### ISSUE TITLE
MultiLine Textbox doesn't show hint

### ISSUE THREAD

**Issue by ThibaudMZN** [leocb/MaterialSkin#83]
Is there a reason why the multiline textbox doesn't display its hint when empty ? It seems like it should be the case to work the same way as other input types.

**Comment by leocb** [comment]
The textbox is a special case in this lib, Microsoft didn't give developers a way to easily draw custom textbox, like they did the rest of the controls, so I use richtextbox with a lot of workarounds to make it work. By hint I assume the one that displays when the user hovers the mouse over a component. This shouldn't be necessary as the material version has a embedded placeholder you can use

**Comment by leocb** [comment]
I'll be closing this as it doesn't seem like a bug. This lib supports only Material designs principles. a hint when hovering the mouse over components is not one of them.
