### ISSUE TITLE
WindowState Maximized cover windows taskbar

### ISSUE THREAD

**Issue by ThibaudMZN** [leocb/MaterialSkin#84]
If a MaterialForm is maximized with the default top right button, it displays correctly, however if you set WindowState to Maximized it covers the windows taskbar.

You can deal with it by setting the maximum size to the working area, like so :

`this.MaximumSize = Screen.PrimaryScreen.WorkingArea.Size;`

**Comment by leocb** [comment]
Thanks for reporting, I'll take a look
