### ISSUE TITLE
Black color around controls

### ISSUE THREAD

**Issue by merco** [leocb/MaterialSkin#86]
![immagine](https://user-images.githubusercontent.com/1032335/81221427-1b80de80-8fe3-11ea-8743-23fc657b1030.png)
Theme is not applied correctly to textbox. When TB receive focus I get Black background and black textcolor....
What can I check ?

this is my colorscheme
  Dim SkinManager As MaterialSkinManager = MaterialSkinManager.Instance

    SkinManager.EnforceBackcolorOnAllComponents = True

    SkinManager.AddFormToManage(Me)
    SkinManager.Theme = MaterialSkinManager.Themes.LIGHT
    SkinManager.ColorScheme = New ColorScheme(Primary.Indigo500, Primary.Indigo700, Primary.Indigo100, Accent.Pink200, TextShade.WHITE)

**Comment by leocb** [comment]
Thanks for reporting.
Are you placing the textbox directly on the form? try placing it inside a container, like a `panel` and see if it fixes your issue.

**Comment by merco** [comment]
it's in a VB.net project, inside a flowlayoutpanel.
But also inside a tabPage.
Let me if I have to do some chek in VB, I'm using the source files.

**Comment by merco** [comment]
![immagine](https://user-images.githubusercontent.com/1032335/81265885-2029af00-9044-11ea-8a25-bc43730e9f98.png)

... and if you check this image... some strange also in buttons... there is a black background around the round corner...

**Comment by leocb** [comment]
In all of those cases, the lib uses the parent color to fill in the transparent sections of the controls. Seems like it may be a VB.net issue. I'll run some tests.

**Comment by merco** [comment]
in another vb form withouth drawerTabControl it's ok

**Comment by leocb** [comment]
hmm interesting. this may have to do with the default "transparent" background color on the drawerTabControl, but it usually only affects the design time and works correctly on runtime. related to #52 
Try setting the tabControl backcolor  to white, see if it fixes your issue

**Comment by merco** [comment]
![immagine](https://user-images.githubusercontent.com/1032335/81339002-cfe73700-90ad-11ea-88c7-7f16016369e4.png)
 YESSSS! and the buttons are round now ! Thank you leo for this trick.. for me is good.

**Comment by leocb** [comment]
You mean a combobox with images along the side of the text? There's not and I don't believe it's something I'd add 😛

**Comment by merco** [comment]
OOOOOOOOOOOOK!
