### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by garciaaa** [leocb/MaterialSkin#92]
There is problem in NativeTextRenderer while using non-english national characters (Russian in my case). Multiline render used in label control shows wrong characters.
It can be fixed adding charset while importing "DrawText" from user32.dll like this:
`[DllImport("user32.dll", CharSet = CharSet.Auto)]`
instead of
`[DllImport("user32.dll")]`
I dunno why, but gdi32's TextOut do not cause any problem with charset.
(Russian Win7, Win10, .net 4.x, .net core 3.1)

**Comment by leocb** [comment]
Hi! Thank you for this info, related to #10. I'll fix this ASAP

**Comment by garciaaa** [comment]
To show off problem there are Russian letters shown nearby nearby chinese in #10. Roboto fonts you ship with your great package DOES contain cyrillic (russian) subset

**Comment by leocb** [comment]
Yeah, I didn't know how to fix it, I never messed with different encoding on the same app, thanks for finding out such an easy fix. Feel free to open a PR
