### ISSUE TITLE
Align text in materialButton not possible.

### ISSUE THREAD

**Issue by sabodh** [leocb/MaterialSkin#95]
Hi is there any way to align text in material button.?I used MiddleLeft but it didn't worked for me.
![Capture](https://user-images.githubusercontent.com/30169371/82916750-14207580-9f90-11ea-9b31-12ffcb73f361.PNG)

**Comment by leocb** [comment]
Hi, buttons should only occupy the space the need, even tough I support "manual sizing" on the buttons, the text should always be in the middle, aka: I don't take the user-specified alignment into account when rendering the buttons. That said, this a open-source project and you're free to change the lib however you want, just add the alignment parameter on the text rendering [in this line of code](https://github.com/leocb/MaterialSkin/blob/f657ca1ac4a938fbae2fcca2e1bf8501b91e1350/MaterialSkin/Controls/MaterialButton.cs#L359)

As a side note: it looks like you're build a menu, try using the drawer instead. see the Wiki entry [here](https://github.com/leocb/MaterialSkin/wiki/How-to-use-the-Drawer) on how to use it.

**Comment by sabodh** [comment]
Hi @leocb , thanks for the replay, you mentioned is correct I am trying to create a menu. I used the drawer layout and able to customise the pages. I tried to crate a menu like open navigation without showing the hamburger menu and the blue panel. I failed to customise that, so that is why I used to create a new menu.

![Capture](https://user-images.githubusercontent.com/30169371/82921243-cad32480-9f95-11ea-967d-79d26a8159f4.PNG)

**Comment by leocb** [comment]
you want the menu to be always open? that's not recommended as you take up precious space on the screen for something that won't be useful all the time. if you REALLY want to do it, modify the MaterialForm control code: remove references to the `overlay` form, set `autohide` to false and remove the drawing and interaction of the `drawer icon`

**Comment by leocb** [comment]
I'll be closing this as there's not a problem to be fixed on this issue.
If you find a bug, feel free to open another one
thanks! :)
